<?php

namespace App\Services;

use App\Models\Language;
use App\Models\SyncRun;
use App\Models\Url;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Throwable;

class SyncService
{
    // A cache lock instead of an in-memory flag: artisan runs as a fresh process each
    // invocation (cron-triggered), so "is a sync running" state can't live in memory.
    private const LOCK_KEY = 'sitemap-sync-lock';

    public function __construct(
        private readonly SitemapFetcherService $fetcher,
        private readonly UrlClassifierService $classifier,
        private readonly SettingsService $settings,
    ) {}

    public function isRunning(): bool
    {
        $lock = Cache::lock(self::LOCK_KEY, 600);
        if ($lock->get()) {
            // Nobody was holding it - we just grabbed it ourselves, so release immediately.
            $lock->release();

            return false;
        }

        return true;
    }

    /**
     * @return array{sync_run_id:int, total_fetched:int, added:int, updated:int, removed:int}
     */
    public function runSync(): array
    {
        $lock = Cache::lock(self::LOCK_KEY, 600);
        if (! $lock->get()) {
            throw new \RuntimeException('A sync is already in progress');
        }

        try {
            return $this->doSync();
        } finally {
            $lock->release();
        }
    }

    private function doSync(): array
    {
        $syncRun = SyncRun::query()->create(['status' => SyncRun::RUNNING]);
        Log::info("Sync run {$syncRun->id} started");

        try {
            $sourceUrl = $this->settings->getSourceSitemapUrl();
            $fetched = $this->fetcher->fetchAll($sourceUrl);

            $seenSourceUrls = [];
            $added = 0;
            $updated = 0;

            foreach ($fetched as $entry) {
                $seenSourceUrls[] = $entry['loc'];
                $classified = $this->classifier->classify($entry['loc']);
                $lastmod = $entry['lastmod'] ? new \DateTimeImmutable($entry['lastmod']) : null;

                $existing = Url::query()->where('source_url', $entry['loc'])->first();

                if (! $existing) {
                    Url::query()->create([
                        'source_url' => $entry['loc'],
                        'path' => $classified['path'],
                        'lang' => $classified['lang'],
                        'pattern_type' => $classified['pattern_type'],
                        'slug' => $classified['slug'],
                        'group_key' => $classified['group_key'],
                        'source_lastmod' => $lastmod,
                        'is_hidden' => $classified['default_hidden'],
                        'is_active' => true,
                        'first_seen_at' => now(),
                        'last_seen_at' => now(),
                    ]);
                    $added++;
                } else {
                    // Manually-recategorized URLs keep the admin's choice; only re-classify untouched ones.
                    $existing->update([
                        'path' => $classified['path'],
                        'lang' => $classified['lang'],
                        'pattern_type' => $existing->is_manual ? $existing->pattern_type : $classified['pattern_type'],
                        'slug' => $classified['slug'],
                        'group_key' => $existing->is_manual ? $existing->group_key : $classified['group_key'],
                        'source_lastmod' => $lastmod,
                        'is_active' => true,
                        'last_seen_at' => now(),
                    ]);
                    $updated++;
                }
            }

            $defaultLang = Language::query()->where('is_default', true)->value('code') ?? 'en';

            // Anything previously fetched but absent from this run has disappeared from the source sitemap.
            // We don't delete it (an admin may have opinions about it); we just flag it inactive.
            //
            // Blog translations generated by BlogAiTranslationService are a deliberate exception:
            // their source_url is a *guessed* URL pattern the admin hasn't necessarily published
            // anywhere yet, so it's expected to be absent from the sitemap until they actually do
            // and BlogTranslationDetectionService confirms it live (which sets
            // translation_checked_at). Without this exclusion, every not-yet-published AI
            // translation would get silently deactivated on the very next sync (as often as every
            // few hours) - which made a topic's translations look entirely lost from the panel,
            // even though nothing had actually been removed from the real site. A translation that
            // *has* been confirmed live is still pruned normally if it later vanishes from the
            // sitemap - that's a real removal, not an unpublished draft.
            $removed = Url::query()
                ->where('is_active', true)
                ->whereNotIn('source_url', $seenSourceUrls)
                ->where(function ($query) use ($defaultLang) {
                    $query->where('pattern_type', '!=', 'BLOG')
                        ->orWhere('lang', $defaultLang)
                        ->orWhereNotNull('translation_checked_at');
                })
                ->update(['is_active' => false]);

            $syncRun->update([
                'status' => SyncRun::SUCCESS,
                'finished_at' => now(),
                'total_fetched' => count($fetched),
                'added' => $added,
                'updated' => $updated,
                'removed' => $removed,
            ]);

            Log::info("Sync run {$syncRun->id} finished: fetched=" . count($fetched) . " added={$added} updated={$updated} removed={$removed}");

            return [
                'sync_run_id' => $syncRun->id,
                'total_fetched' => count($fetched),
                'added' => $added,
                'updated' => $updated,
                'removed' => $removed,
            ];
        } catch (Throwable $e) {
            $syncRun->update([
                'status' => SyncRun::FAILED,
                'finished_at' => now(),
                'error_message' => $e->getMessage(),
            ]);
            Log::error("Sync run {$syncRun->id} failed: {$e->getMessage()}");
            throw $e;
        }
    }
}
