<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * The 20 starter reviews shipped with the reviews table were Persian-only. Reviews are shown
     * to visitors in their own language (Review.lang), so every other language the panel already
     * translates into needs its own set too, rather than falling back to Persian for everyone
     * else. 20 reviews per language, matching the same product/theme variety as the original
     * Persian batch (delivery speed, price, support, no drop-off, repeat customers, referrals).
     *
     * Language codes here match what this app already uses elsewhere for the same languages
     * (Category/Service translation, Language::code) - if any of the codes below don't match
     * what's actually configured in this panel's Languages page, the affected rows just won't
     * surface for that language until their `lang` value is corrected (they're plain strings,
     * no FK), so it's a safe mismatch to fix later rather than a hard failure.
     */
    public function up(): void
    {
        $now = now();

        $reviewsByLang = [
            'en' => [
                ['Sarah Mitchell', 5, "I've ordered Instagram followers from here three times now and every single time delivery started within minutes. Never had a single drop.", 'Instagram Followers', 'United States', 'US'],
                ['James Carter', 5, 'Telegram views for my channel came in steady over about a day, exactly like they said. Support answered my ticket in under ten minutes too.', 'Telegram Post Views', 'United Kingdom', 'GB'],
                ['Olivia Bennett', 4, 'Good quality followers, just took a bit longer to start than I expected. Still got everything I paid for.', 'Instagram Followers', 'Canada', 'CA'],
                ['Daniel Reyes', 5, "Cheapest prices I've found for TikTok followers and the quality is actually solid, not bot accounts.", 'TikTok Followers', 'United States', 'US'],
                ['Emma Wilson', 5, 'My YouTube views came in gradually over a couple of days which looked way more natural than instant delivery from other sites.', 'YouTube Views', 'Australia', 'AU'],
                ['Michael Chen', 5, 'Ordered Telegram members for a new channel launch and it genuinely helped get organic growth going after.', 'Telegram Members', 'United States', 'US'],
                ['Grace Thompson', 4, 'Support took a while to reply on a weekend but they did sort out my order eventually.', 'Instagram Likes', 'United Kingdom', 'GB'],
                ['Ryan Foster', 5, "Been using this panel for months now for different accounts, never once had a refund issue or missing order.", 'Instagram Followers', 'United States', 'US'],
                ['Chloe Anderson', 5, "The story views service is perfect for my shop's page, delivery is always fast and consistent.", 'Instagram Story Views', 'Canada', 'CA'],
                ['Ethan Brooks', 5, 'Way more affordable than the other panels I tried and the followers actually look real, not empty accounts.', 'Instagram Followers', 'United States', 'US'],
                ['Lily Parker', 5, 'Ordered Twitter likes for a launch post and they came in within the hour, exactly as promised.', 'Twitter Likes', 'United Kingdom', 'GB'],
                ['Nathan Cooper', 4, 'Solid service overall, wish there were more quality tiers to choose from but no complaints on delivery.', 'YouTube Subscribers', 'Australia', 'AU'],
                ['Sophia Ramirez', 5, "This is my go-to panel now, I've recommended it to two other people who run shops on Instagram.", 'Instagram Followers', 'United States', 'US'],
                ['Benjamin Scott', 5, 'Telegram post views delivered exactly on schedule, channel looks a lot more active now.', 'Telegram Post Views', 'Canada', 'CA'],
                ['Ava Mitchell', 5, "Support walked me through setting up my first order since I'd never used a panel like this before.", 'TikTok Likes', 'United States', 'US'],
                ['Lucas Bailey', 4, 'Delivery was a little slower than advertised but customer service kept me updated the whole time.', 'Instagram Followers', 'United Kingdom', 'GB'],
                ['Isabella Turner', 5, 'No drop at all after a month, which is more than I can say for other sites I have tried.', 'Instagram Followers', 'United States', 'US'],
                ['Henry Ward', 5, 'Cheap, fast, and reliable - exactly what I needed for growing my new channel.', 'Telegram Members', 'Australia', 'AU'],
                ['Mia Coleman', 5, 'I run a small business account and this panel has genuinely helped with visibility on new posts.', 'Instagram Likes', 'United States', 'US'],
                ['Jack Murphy', 5, "Ordered YouTube views for a client's channel, came in gradually and looked completely natural.", 'YouTube Views', 'Canada', 'CA'],
            ],
            'ar' => [
                ['سارة العتيبي', 5, 'طلبت متابعين انستقرام من هذا الموقع أكثر من مرة، والتسليم دايم سريع وما صار عندي أي نقصان بالمتابعين.', 'متابعين انستقرام', 'السعودية', 'SA'],
                ['محمد الفهد', 5, 'خدمة مشاهدات تيليجرام ممتازة، وصلت تدريجياً خلال يوم واحد بالضبط زي ما وعدوا.', 'مشاهدات تيليجرام', 'السعودية', 'SA'],
                ['نور إبراهيم', 4, 'الجودة كويسة بس التسليم أخذ وقت أطول شوي من المتوقع.', 'متابعين تيك توك', 'مصر', 'EG'],
                ['عبدالله القحطاني', 5, 'الأسعار من أرخص اللي شفتها والدعم الفني يرد بسرعة على أي استفسار.', 'لايكات انستقرام', 'السعودية', 'SA'],
                ['فاطمة الزهراني', 5, 'استخدمت الموقع لقناتي في تيليجرام وساعدني كثير في زيادة الأعضاء بشكل طبيعي.', 'أعضاء تيليجرام', 'الإمارات', 'AE'],
                ['خالد المطيري', 5, 'من أفضل المواقع اللي جربتها، ما صار عندي أي مشكلة بالطلبات من أول يوم.', 'متابعين انستقرام', 'السعودية', 'SA'],
                ['ريم الحربي', 4, 'الدعم الفني تأخر شوي بالرد لكن حلوا المشكلة في النهاية.', 'مشاهدات ستوري', 'مصر', 'EG'],
                ['يوسف الشمري', 5, 'جودة المتابعين حلوة جداً، مو حسابات وهمية وفاضية.', 'متابعين تيك توك', 'السعودية', 'SA'],
                ['لينا عبدالرحمن', 5, 'صار لي أشهر أطلب من نفس الموقع، ما توقفت خدمة ولا مرة.', 'لايكات انستقرام', 'الإمارات', 'AE'],
                ['عمر الدوسري', 5, 'التسليم كان تدريجي وطبيعي جداً على مشاهدات يوتيوب، ما لاحظ أحد إنها مو حقيقية.', 'مشاهدات يوتيوب', 'السعودية', 'SA'],
                ['هند القرني', 5, 'رشحت الموقع لصديقاتي اللي عندهم متاجر على انستقرام، كلهم انبسطوا بالنتيجة.', 'متابعين انستقرام', 'مصر', 'EG'],
                ['سلطان العنزي', 4, 'الخدمة زينة بس أتمنى يضيفون خيارات جودة أكثر للمتابعين.', 'مشتركين يوتيوب', 'السعودية', 'SA'],
                ['جواهر السبيعي', 5, 'أول مرة أستخدم موقع من هذا النوع والدعم شرح لي كل خطوة بصبر.', 'لايكات تيك توك', 'الإمارات', 'AE'],
                ['فهد آل سعود', 5, 'ما نزل عندي ولا متابع بعد شهر كامل، شيء ممتاز مقارنة بمواقع ثانية جربتها.', 'متابعين انستقرام', 'السعودية', 'SA'],
                ['منى الغامدي', 5, 'مشاهدات تيليجرام وصلت بالضبط بالوقت المحدد، القناة صارت تبان أنشط بكثير.', 'مشاهدات تيليجرام', 'مصر', 'EG'],
                ['تركي البقمي', 4, 'التسليم كان أبطأ شوي من الموعد المذكور بس خدمة العملاء متابعة معي أول بأول.', 'متابعين انستقرام', 'السعودية', 'SA'],
                ['عبير النعيمي', 5, 'رخيص وسريع وموثوق، بالضبط اللي كنت أبحث عنه لقناتي الجديدة.', 'أعضاء تيليجرام', 'الإمارات', 'AE'],
                ['سعد الشهري', 5, 'عندي حساب تجاري صغير والموقع فعلاً ساعدني أزيد التفاعل على منشوراتي.', 'لايكات انستقرام', 'السعودية', 'SA'],
                ['دانة العجمي', 5, 'طلبت مشاهدات يوتيوب لقناة عميل، وصلت تدريجياً وبشكل طبيعي جداً.', 'مشاهدات يوتيوب', 'الإمارات', 'AE'],
                ['بندر الرشيدي', 5, 'من أفضل تجاربي مع مواقع الخدمات الرقمية، بدون أي مبالغة.', 'متابعين تيك توك', 'السعودية', 'SA'],
            ],
            'tr' => [
                ['Elif Yılmaz', 5, 'Instagram takipçi siparişi birkaç kez verdim, her seferinde teslimat çok hızlı başladı ve hiç düşüş yaşamadım.', 'Instagram Takipçi', 'Türkiye', 'TR'],
                ['Mehmet Kaya', 5, 'Telegram kanalım için izlenme aldım, tam bir gün içinde kademeli olarak geldi, söyledikleri gibi.', 'Telegram İzlenme', 'Türkiye', 'TR'],
                ['Zeynep Demir', 4, 'Kalite iyiydi ama teslimat beklediğimden biraz geç başladı.', 'TikTok Takipçi', 'Azerbaycan', 'AZ'],
                ['Ahmet Çelik', 5, 'Fiyatlar gerçekten uygun ve destek ekibi her sorumu hızlıca yanıtladı.', 'Instagram Beğeni', 'Türkiye', 'TR'],
                ['Ayşe Şahin', 5, 'Telegram kanalıma üye aldım ve organik büyümeye de gerçekten katkısı oldu.', 'Telegram Üye', 'Türkiye', 'TR'],
                ['Emre Arslan', 5, 'Aylardır bu siteden alışveriş yapıyorum, hiçbir zaman sorun yaşamadım.', 'Instagram Takipçi', 'Türkiye', 'TR'],
                ['Fatma Yıldız', 4, 'Destek hafta sonu biraz geç döndü ama sonunda sorunumu çözdüler.', 'Instagram Hikaye İzlenme', 'Azerbaycan', 'AZ'],
                ['Burak Öztürk', 5, 'Takipçi kalitesi gerçekten iyi, boş hesaplar değil.', 'TikTok Takipçi', 'Türkiye', 'TR'],
                ['Selin Aydın', 5, 'Bu siteyi mağazası olan iki arkadaşıma da önerdim, onlar da çok memnun kaldı.', 'Instagram Takipçi', 'Türkiye', 'TR'],
                ['Caner Koç', 5, 'YouTube izlenmeleri kademeli geldi, hiç yapay durmuyor.', 'YouTube İzlenme', 'Türkiye', 'TR'],
                ['Deniz Aksoy', 5, 'Twitter beğenileri bir saat içinde geldi, tam söz verdikleri gibi.', 'Twitter Beğeni', 'Azerbaycan', 'AZ'],
                ['Gökhan Polat', 4, 'Genel olarak iyi ama daha fazla kalite seçeneği olsa güzel olur.', 'YouTube Abone', 'Türkiye', 'TR'],
                ['Ceren Er', 5, 'İlk defa böyle bir site kullanıyordum, destek ekibi adım adım yardımcı oldu.', 'TikTok Beğeni', 'Türkiye', 'TR'],
                ['Onur Yücel', 5, 'Bir ay sonra bile hiç düşüş olmadı, başka sitelerde böyle olmamıştı.', 'Instagram Takipçi', 'Türkiye', 'TR'],
                ['Merve Kılıç', 5, 'Telegram izlenmeleri tam zamanında geldi, kanalım artık çok daha aktif görünüyor.', 'Telegram İzlenme', 'Türkiye', 'TR'],
                ['Tolga Doğan', 4, 'Teslimat biraz yavaş başladı ama destek sürekli bilgi verdi.', 'Instagram Takipçi', 'Azerbaycan', 'AZ'],
                ['İrem Aktaş', 5, 'Ucuz, hızlı ve güvenilir, yeni kanalım için tam aradığım şeydi.', 'Telegram Üye', 'Türkiye', 'TR'],
                ['Serkan Bulut', 5, 'Küçük bir işletme hesabım var ve bu site gerçekten etkileşimi artırmama yardımcı oldu.', 'Instagram Beğeni', 'Türkiye', 'TR'],
                ['Aslı Korkmaz', 5, 'Bir müşterim için YouTube izlenmesi aldım, kademeli ve çok doğal göründü.', 'YouTube İzlenme', 'Türkiye', 'TR'],
                ['Hakan Şimşek', 5, 'Denediğim en iyi panel, hiç abartmıyorum.', 'TikTok Takipçi', 'Türkiye', 'TR'],
            ],
            'ru' => [
                ['Анна Смирнова', 5, 'Заказывала подписчиков в Instagram уже несколько раз, доставка всегда начинается быстро и без потерь.', 'Подписчики Instagram', 'Россия', 'RU'],
                ['Дмитрий Иванов', 5, 'Просмотры для Telegram-канала пришли постепенно за сутки, точно как обещали.', 'Просмотры Telegram', 'Россия', 'RU'],
                ['Елена Кузнецова', 4, 'Качество хорошее, но доставка началась немного позже, чем я ожидала.', 'Подписчики TikTok', 'Казахстан', 'KZ'],
                ['Сергей Попов', 5, 'Цены реально ниже, чем у других панелей, а поддержка отвечает быстро.', 'Лайки Instagram', 'Россия', 'RU'],
                ['Ольга Соколова', 5, 'Заказала участников для своего Telegram-канала, это правда помогло с органическим ростом.', 'Участники Telegram', 'Беларусь', 'BY'],
                ['Игорь Морозов', 5, 'Пользуюсь этим сервисом уже несколько месяцев, ни разу не было проблем с заказом.', 'Подписчики Instagram', 'Россия', 'RU'],
                ['Мария Волкова', 4, 'Поддержка ответила не сразу в выходные, но проблему всё же решили.', 'Просмотры историй', 'Казахстан', 'KZ'],
                ['Алексей Лебедев', 5, 'Качество подписчиков реально хорошее, не пустые аккаунты.', 'Подписчики TikTok', 'Россия', 'RU'],
                ['Татьяна Новикова', 5, 'Посоветовала этот сайт двум знакомым с магазинами в Instagram, все остались довольны.', 'Подписчики Instagram', 'Россия', 'RU'],
                ['Виктор Морозов', 5, 'Просмотры на YouTube приходили постепенно, выглядело очень естественно.', 'Просмотры YouTube', 'Беларусь', 'BY'],
                ['Наталья Семёнова', 5, 'Лайки в Twitter пришли в течение часа, ровно как и обещали.', 'Лайки Twitter', 'Россия', 'RU'],
                ['Павел Козлов', 4, 'В целом неплохо, но хотелось бы больше вариантов качества.', 'Подписчики YouTube', 'Казахстан', 'KZ'],
                ['Юлия Фёдорова', 5, 'Впервые пользовалась подобным сервисом, поддержка помогла разобраться с первым заказом.', 'Лайки TikTok', 'Россия', 'RU'],
                ['Роман Егоров', 5, 'Через месяц не было ни единого отписавшегося, чего не скажешь о других сайтах.', 'Подписчики Instagram', 'Россия', 'RU'],
                ['Светлана Павлова', 5, 'Просмотры в Telegram пришли точно в срок, канал теперь выглядит намного активнее.', 'Просмотры Telegram', 'Россия', 'RU'],
                ['Артём Никитин', 4, 'Доставка началась чуть медленнее заявленного, но поддержка держала меня в курсе.', 'Подписчики Instagram', 'Беларусь', 'BY'],
                ['Ксения Захарова', 5, 'Дёшево, быстро и надёжно - именно то, что нужно было для нового канала.', 'Участники Telegram', 'Россия', 'RU'],
                ['Денис Орлов', 5, 'У меня небольшой бизнес-аккаунт, и этот сервис реально помог с вовлечённостью.', 'Лайки Instagram', 'Россия', 'RU'],
                ['Виктория Андреева', 5, 'Заказывала просмотры YouTube для клиента, пришли постепенно и выглядели естественно.', 'Просмотры YouTube', 'Казахстан', 'KZ'],
                ['Максим Григорьев', 5, 'Лучший сервис из всех, что я пробовал, без преувеличения.', 'Подписчики TikTok', 'Россия', 'RU'],
            ],
            'es' => [
                ['Lucía Fernández', 5, 'Pedí seguidores de Instagram varias veces y la entrega siempre empieza rápido, sin caídas.', 'Seguidores Instagram', 'España', 'ES'],
                ['Carlos Martínez', 5, 'Las vistas de Telegram llegaron poco a poco durante un día completo, tal como prometieron.', 'Vistas Telegram', 'México', 'MX'],
                ['Valentina López', 4, 'La calidad es buena pero la entrega tardó un poco más de lo esperado.', 'Seguidores TikTok', 'Argentina', 'AR'],
                ['Diego Sánchez', 5, 'Los precios son los más baratos que he encontrado y el soporte responde rápido.', 'Me gusta Instagram', 'España', 'ES'],
                ['Camila Torres', 5, 'Compré miembros para mi canal de Telegram y realmente ayudó con el crecimiento orgánico.', 'Miembros Telegram', 'Colombia', 'CO'],
                ['Javier Ramírez', 5, 'Llevo meses usando este sitio y nunca he tenido problemas con mis pedidos.', 'Seguidores Instagram', 'España', 'ES'],
                ['Isabella Gómez', 4, 'El soporte tardó un poco en responder el fin de semana, pero resolvieron todo al final.', 'Vistas de historias', 'México', 'MX'],
                ['Andrés Díaz', 5, 'La calidad de los seguidores es muy buena, no son cuentas vacías.', 'Seguidores TikTok', 'España', 'ES'],
                ['Sofía Morales', 5, 'Recomendé este sitio a dos amigas con tiendas en Instagram y quedaron encantadas.', 'Seguidores Instagram', 'Argentina', 'AR'],
                ['Mateo Herrera', 5, 'Las vistas de YouTube llegaron gradualmente, se ven completamente naturales.', 'Vistas YouTube', 'España', 'ES'],
                ['Daniela Castro', 5, 'Los me gusta de Twitter llegaron en menos de una hora, tal como decían.', 'Me gusta Twitter', 'Colombia', 'CO'],
                ['Pablo Ortiz', 4, 'En general está bien, aunque me gustaría que hubiera más opciones de calidad.', 'Suscriptores YouTube', 'México', 'MX'],
                ['Martina Vargas', 5, 'Era la primera vez que usaba un panel así y el soporte me ayudó con todo el proceso.', 'Me gusta TikTok', 'España', 'ES'],
                ['Alejandro Ruiz', 5, 'Después de un mes no perdí ni un solo seguidor, algo que no pasó en otros sitios.', 'Seguidores Instagram', 'Argentina', 'AR'],
                ['Renata Flores', 5, 'Las vistas de Telegram llegaron exactamente a tiempo, mi canal se ve mucho más activo.', 'Vistas Telegram', 'España', 'ES'],
                ['Gabriel Molina', 4, 'La entrega empezó un poco más lento de lo anunciado, pero el soporte me mantuvo informado.', 'Seguidores Instagram', 'México', 'MX'],
                ['Antonella Reyes', 5, 'Barato, rápido y confiable, justo lo que necesitaba para mi canal nuevo.', 'Miembros Telegram', 'Colombia', 'CO'],
                ['Rodrigo Silva', 5, 'Tengo una cuenta de negocio pequeña y este sitio realmente ayudó con la interacción.', 'Me gusta Instagram', 'España', 'ES'],
                ['Florencia Núñez', 5, 'Pedí vistas de YouTube para un cliente, llegaron gradualmente y se veían muy naturales.', 'Vistas YouTube', 'Argentina', 'AR'],
                ['Iván Guerrero', 5, 'El mejor servicio que he probado, sin exagerar.', 'Seguidores TikTok', 'España', 'ES'],
            ],
            'fr' => [
                ['Camille Dubois', 5, "J'ai commandé des abonnés Instagram plusieurs fois, la livraison démarre toujours vite et sans perte.", 'Abonnés Instagram', 'France', 'FR'],
                ['Antoine Lefebvre', 5, 'Les vues Telegram sont arrivées progressivement sur une journée complète, exactement comme promis.', 'Vues Telegram', 'France', 'FR'],
                ['Chloé Moreau', 4, 'La qualité était bonne mais la livraison a mis un peu plus de temps que prévu.', 'Abonnés TikTok', 'Belgique', 'BE'],
                ['Julien Bernard', 5, 'Les prix sont les plus bas que j\'ai trouvés et le support répond rapidement.', "J'aime Instagram", 'France', 'FR'],
                ['Manon Petit', 5, "J'ai acheté des membres pour ma chaîne Telegram, ça a vraiment aidé la croissance organique.", 'Membres Telegram', 'Maroc', 'MA'],
                ['Nicolas Roux', 5, "J'utilise ce site depuis des mois, jamais eu de souci avec mes commandes.", 'Abonnés Instagram', 'France', 'FR'],
                ['Léa Girard', 4, 'Le support a mis du temps à répondre le week-end mais tout a fini par être résolu.', 'Vues de stories', 'Canada', 'CA'],
                ['Maxime Fontaine', 5, 'La qualité des abonnés est vraiment bonne, pas des comptes vides.', 'Abonnés TikTok', 'France', 'FR'],
                ['Emma Rousseau', 5, "J'ai recommandé ce site à deux amies qui ont des boutiques sur Instagram, elles sont ravies.", 'Abonnés Instagram', 'France', 'FR'],
                ['Hugo Simon', 5, 'Les vues YouTube sont arrivées progressivement, ça a l\'air totalement naturel.', 'Vues YouTube', 'France', 'FR'],
                ['Sarah Laurent', 5, 'Les likes Twitter sont arrivés en moins d\'une heure, exactement comme promis.', "J'aime Twitter", 'Belgique', 'BE'],
                ['Théo Michel', 4, "Globalement bien, mais j'aimerais plus d'options de qualité.", 'Abonnés YouTube', 'France', 'FR'],
                ['Inès Garcia', 5, "C'était ma première fois avec ce genre de site, le support m'a guidée à chaque étape.", "J'aime TikTok", 'France', 'FR'],
                ['Louis David', 5, "Après un mois, aucune perte d'abonnés, contrairement à d'autres sites que j'ai essayés.", 'Abonnés Instagram', 'Canada', 'CA'],
                ['Zoé Bertrand', 5, 'Les vues Telegram sont arrivées pile à temps, ma chaîne paraît beaucoup plus active.', 'Vues Telegram', 'France', 'FR'],
                ['Adam Morel', 4, 'La livraison a démarré un peu plus lentement que prévu mais le support m\'a tenu informé.', 'Abonnés Instagram', 'Maroc', 'MA'],
                ['Jade Fournier', 5, "Pas cher, rapide et fiable, exactement ce qu'il fallait pour ma nouvelle chaîne.", 'Membres Telegram', 'France', 'FR'],
                ['Clément Vincent', 5, "J'ai un petit compte professionnel et ce site a vraiment aidé l'engagement.", "J'aime Instagram", 'France', 'FR'],
                ['Anaïs Muller', 5, "J'ai commandé des vues YouTube pour un client, arrivées progressivement et très naturelles.", 'Vues YouTube', 'Belgique', 'BE'],
                ['Baptiste Leroy', 5, "Le meilleur service que j'ai essayé, sans exagération.", 'Abonnés TikTok', 'France', 'FR'],
            ],
            'de' => [
                ['Lena Schmidt', 5, 'Ich habe schon mehrmals Instagram-Follower bestellt, die Lieferung startet immer schnell und ohne Verluste.', 'Instagram-Follower', 'Deutschland', 'DE'],
                ['Jonas Fischer', 5, 'Die Telegram-Aufrufe kamen nach und nach innerhalb eines Tages, genau wie versprochen.', 'Telegram-Aufrufe', 'Deutschland', 'DE'],
                ['Hannah Weber', 4, 'Die Qualität war gut, aber die Lieferung hat etwas länger gedauert als erwartet.', 'TikTok-Follower', 'Österreich', 'AT'],
                ['Lukas Meyer', 5, 'Die Preise sind die günstigsten, die ich gefunden habe, und der Support antwortet schnell.', 'Instagram-Likes', 'Deutschland', 'DE'],
                ['Emilia Wagner', 5, 'Ich habe Mitglieder für meinen Telegram-Kanal gekauft, das hat dem organischen Wachstum wirklich geholfen.', 'Telegram-Mitglieder', 'Schweiz', 'CH'],
                ['Felix Becker', 5, 'Ich nutze diese Seite seit Monaten, nie Probleme mit meinen Bestellungen gehabt.', 'Instagram-Follower', 'Deutschland', 'DE'],
                ['Marie Hoffmann', 4, 'Der Support hat am Wochenende etwas länger gebraucht, aber am Ende war alles geklärt.', 'Story-Views', 'Österreich', 'AT'],
                ['Paul Schäfer', 5, 'Die Qualität der Follower ist wirklich gut, keine leeren Konten.', 'TikTok-Follower', 'Deutschland', 'DE'],
                ['Sophie Koch', 5, 'Ich habe diese Seite zwei Freundinnen mit Instagram-Shops empfohlen, sie waren begeistert.', 'Instagram-Follower', 'Deutschland', 'DE'],
                ['Tim Richter', 5, 'Die YouTube-Aufrufe kamen allmählich, sah total natürlich aus.', 'YouTube-Aufrufe', 'Deutschland', 'DE'],
                ['Laura Klein', 5, 'Die Twitter-Likes kamen innerhalb einer Stunde, genau wie versprochen.', 'Twitter-Likes', 'Schweiz', 'CH'],
                ['Jan Wolf', 4, 'Insgesamt gut, aber ich hätte gerne mehr Qualitätsoptionen.', 'YouTube-Abonnenten', 'Deutschland', 'DE'],
                ['Nele Schröder', 5, 'War das erste Mal, dass ich so eine Seite genutzt habe, der Support hat mir bei allem geholfen.', 'TikTok-Likes', 'Deutschland', 'DE'],
                ['Moritz Neumann', 5, 'Nach einem Monat kein einziger Follower-Verlust, anders als bei anderen Seiten.', 'Instagram-Follower', 'Österreich', 'AT'],
                ['Johanna Schwarz', 5, 'Die Telegram-Aufrufe kamen genau pünktlich an, mein Kanal wirkt jetzt viel aktiver.', 'Telegram-Aufrufe', 'Deutschland', 'DE'],
                ['David Zimmermann', 4, 'Die Lieferung startete etwas langsamer als angekündigt, aber der Support hat mich informiert.', 'Instagram-Follower', 'Schweiz', 'CH'],
                ['Anna-Lena Braun', 5, 'Günstig, schnell und zuverlässig, genau das, was ich für meinen neuen Kanal brauchte.', 'Telegram-Mitglieder', 'Deutschland', 'DE'],
                ['Simon Krüger', 5, 'Ich habe ein kleines Business-Konto und diese Seite hat wirklich beim Engagement geholfen.', 'Instagram-Likes', 'Deutschland', 'DE'],
                ['Mila Hofmann', 5, 'Ich habe YouTube-Aufrufe für einen Kunden bestellt, kamen allmählich und sahen natürlich aus.', 'YouTube-Aufrufe', 'Österreich', 'AT'],
                ['Elias Lange', 5, 'Der beste Service, den ich bisher ausprobiert habe, ohne Übertreibung.', 'TikTok-Follower', 'Deutschland', 'DE'],
            ],
            'it' => [
                ['Giulia Ferrari', 5, 'Ho ordinato follower Instagram diverse volte, la consegna parte sempre velocemente e senza cali.', 'Follower Instagram', 'Italia', 'IT'],
                ['Marco Rossi', 5, 'Le visualizzazioni Telegram sono arrivate gradualmente nell\'arco di un giorno intero, esattamente come promesso.', 'Visualizzazioni Telegram', 'Italia', 'IT'],
                ['Chiara Bianchi', 4, "La qualità era buona ma la consegna ha impiegato un po' più del previsto.", 'Follower TikTok', 'Svizzera', 'CH'],
                ['Alessandro Romano', 5, 'I prezzi sono i più bassi che ho trovato e il supporto risponde velocemente.', 'Mi piace Instagram', 'Italia', 'IT'],
                ['Francesca Colombo', 5, 'Ho comprato membri per il mio canale Telegram, ha davvero aiutato la crescita organica.', 'Membri Telegram', 'Italia', 'IT'],
                ['Davide Ricci', 5, 'Uso questo sito da mesi, non ho mai avuto problemi con i miei ordini.', 'Follower Instagram', 'Italia', 'IT'],
                ['Martina Marino', 4, "Il supporto ha risposto un po' lentamente nel weekend ma alla fine hanno risolto tutto.", 'Visualizzazioni storie', 'Svizzera', 'CH'],
                ['Simone Greco', 5, 'La qualità dei follower è davvero buona, non sono account vuoti.', 'Follower TikTok', 'Italia', 'IT'],
                ['Sara Bruno', 5, 'Ho consigliato questo sito a due amiche con negozi su Instagram, erano entusiaste.', 'Follower Instagram', 'Italia', 'IT'],
                ['Federico Costa', 5, 'Le visualizzazioni YouTube sono arrivate gradualmente, sembrava tutto molto naturale.', 'Visualizzazioni YouTube', 'Italia', 'IT'],
                ['Elena Fontana', 5, 'I mi piace su Twitter sono arrivati in meno di un\'ora, esattamente come promesso.', 'Mi piace Twitter', 'Italia', 'IT'],
                ['Riccardo Serra', 4, 'In generale va bene, ma vorrei più opzioni di qualità.', 'Iscritti YouTube', 'Svizzera', 'CH'],
                ['Valentina Conti', 5, 'Era la prima volta che usavo un pannello del genere, il supporto mi ha aiutato passo dopo passo.', 'Mi piace TikTok', 'Italia', 'IT'],
                ['Lorenzo Villa', 5, 'Dopo un mese non ho perso nemmeno un follower, diversamente da altri siti che ho provato.', 'Follower Instagram', 'Italia', 'IT'],
                ['Beatrice Rizzo', 5, 'Le visualizzazioni Telegram sono arrivate puntualissime, il mio canale ora sembra molto più attivo.', 'Visualizzazioni Telegram', 'Italia', 'IT'],
                ['Andrea Lombardi', 4, "La consegna è iniziata un po' più lentamente del previsto ma il supporto mi ha tenuto aggiornato.", 'Follower Instagram', 'Italia', 'IT'],
                ['Giorgia Moretti', 5, 'Economico, veloce e affidabile, esattamente quello che serviva per il mio nuovo canale.', 'Membri Telegram', 'Italia', 'IT'],
                ['Matteo Barbieri', 5, 'Ho un piccolo account aziendale e questo sito ha davvero aiutato il coinvolgimento.', 'Mi piace Instagram', 'Italia', 'IT'],
                ['Alice Gallo', 5, 'Ho ordinato visualizzazioni YouTube per un cliente, arrivate gradualmente e sembravano molto naturali.', 'Visualizzazioni YouTube', 'Svizzera', 'CH'],
                ['Luca Farina', 5, 'Il miglior servizio che abbia mai provato, senza esagerare.', 'Follower TikTok', 'Italia', 'IT'],
            ],
            'bp' => [
                ['Beatriz Souza', 5, 'Já pedi seguidores no Instagram várias vezes e a entrega sempre começa rápido, sem quedas.', 'Seguidores Instagram', 'Brasil', 'BR'],
                ['Gabriel Oliveira', 5, 'As visualizações no Telegram chegaram aos poucos ao longo de um dia inteiro, exatamente como prometido.', 'Visualizações Telegram', 'Brasil', 'BR'],
                ['Larissa Costa', 4, 'A qualidade foi boa mas a entrega demorou um pouco mais do que eu esperava.', 'Seguidores TikTok', 'Portugal', 'PT'],
                ['Rafael Almeida', 5, 'Os preços são os mais baratos que encontrei e o suporte responde rápido.', 'Curtidas Instagram', 'Brasil', 'BR'],
                ['Juliana Pereira', 5, 'Comprei membros para meu canal no Telegram e realmente ajudou no crescimento orgânico.', 'Membros Telegram', 'Brasil', 'BR'],
                ['Thiago Ribeiro', 5, 'Uso esse site há meses e nunca tive problema com meus pedidos.', 'Seguidores Instagram', 'Brasil', 'BR'],
                ['Amanda Carvalho', 4, 'O suporte demorou um pouco no fim de semana mas resolveram tudo no final.', 'Visualizações de stories', 'Portugal', 'PT'],
                ['Bruno Martins', 5, 'A qualidade dos seguidores é muito boa, não são contas vazias.', 'Seguidores TikTok', 'Brasil', 'BR'],
                ['Fernanda Rocha', 5, 'Recomendei esse site para duas amigas que têm loja no Instagram, elas adoraram.', 'Seguidores Instagram', 'Brasil', 'BR'],
                ['Diego Barbosa', 5, 'As visualizações no YouTube chegaram aos poucos, ficou super natural.', 'Visualizações YouTube', 'Brasil', 'BR'],
                ['Camila Nascimento', 5, 'As curtidas no Twitter chegaram em menos de uma hora, exatamente como disseram.', 'Curtidas Twitter', 'Portugal', 'PT'],
                ['Vinícius Araújo', 4, 'No geral é bom, mas eu gostaria de mais opções de qualidade.', 'Inscritos YouTube', 'Brasil', 'BR'],
                ['Letícia Cardoso', 5, 'Era a primeira vez que eu usava um painel assim, o suporte me ajudou em cada passo.', 'Curtidas TikTok', 'Brasil', 'BR'],
                ['Matheus Teixeira', 5, 'Depois de um mês não caiu nenhum seguidor, diferente de outros sites que já usei.', 'Seguidores Instagram', 'Portugal', 'PT'],
                ['Isadora Lima', 5, 'As visualizações no Telegram chegaram no tempo certo, meu canal parece muito mais ativo agora.', 'Visualizações Telegram', 'Brasil', 'BR'],
                ['Eduardo Farias', 4, 'A entrega começou um pouco mais devagar do que o anunciado mas o suporte me manteve informado.', 'Seguidores Instagram', 'Brasil', 'BR'],
                ['Vitória Gomes', 5, 'Barato, rápido e confiável, exatamente o que eu precisava para o meu canal novo.', 'Membros Telegram', 'Brasil', 'BR'],
                ['Leonardo Dias', 5, 'Tenho uma conta comercial pequena e esse site realmente ajudou no engajamento.', 'Curtidas Instagram', 'Brasil', 'BR'],
                ['Marina Correia', 5, 'Pedi visualizações no YouTube para um cliente, chegaram aos poucos e pareciam bem naturais.', 'Visualizações YouTube', 'Portugal', 'PT'],
                ['Rodrigo Pinto', 5, 'O melhor serviço que eu já testei, sem exagero.', 'Seguidores TikTok', 'Brasil', 'BR'],
            ],
            'id' => [
                ['Siti Rahayu', 5, 'Saya sudah beberapa kali pesan followers Instagram, pengirimannya selalu cepat dan tidak pernah turun.', 'Followers Instagram', 'Indonesia', 'ID'],
                ['Budi Santoso', 5, 'Views Telegram datang bertahap selama sehari penuh, persis seperti yang dijanjikan.', 'Views Telegram', 'Indonesia', 'ID'],
                ['Dewi Lestari', 4, 'Kualitasnya bagus tapi pengirimannya agak lebih lama dari yang saya perkirakan.', 'Followers TikTok', 'Malaysia', 'MY'],
                ['Agus Wijaya', 5, 'Harganya paling murah yang pernah saya temukan dan support-nya cepat balas.', 'Likes Instagram', 'Indonesia', 'ID'],
                ['Rina Puspita', 5, 'Saya beli member untuk channel Telegram saya, benar-benar membantu pertumbuhan organik.', 'Member Telegram', 'Indonesia', 'ID'],
                ['Hendra Kusuma', 5, 'Sudah pakai situs ini berbulan-bulan, tidak pernah ada masalah dengan pesanan saya.', 'Followers Instagram', 'Indonesia', 'ID'],
                ['Yuni Anggraini', 4, 'Support agak lama balas di akhir pekan tapi akhirnya masalah saya selesai juga.', 'Views Story', 'Malaysia', 'MY'],
                ['Andi Firmansyah', 5, 'Kualitas followers-nya bagus banget, bukan akun kosong.', 'Followers TikTok', 'Indonesia', 'ID'],
                ['Maya Sari', 5, 'Saya rekomendasikan situs ini ke dua teman yang punya toko di Instagram, mereka senang banget.', 'Followers Instagram', 'Indonesia', 'ID'],
                ['Rizky Ramadhan', 5, 'Views YouTube datang bertahap, kelihatan sangat alami.', 'Views YouTube', 'Indonesia', 'ID'],
                ['Putri Wulandari', 5, 'Likes Twitter datang dalam waktu kurang dari satu jam, persis seperti janji mereka.', 'Likes Twitter', 'Malaysia', 'MY'],
                ['Fajar Nugroho', 4, 'Secara keseluruhan bagus, tapi saya berharap ada lebih banyak pilihan kualitas.', 'Subscriber YouTube', 'Indonesia', 'ID'],
                ['Indah Permata', 5, 'Ini pertama kalinya saya pakai panel seperti ini, support-nya membantu setiap langkahnya.', 'Likes TikTok', 'Indonesia', 'ID'],
                ['Bayu Prasetyo', 5, 'Setelah satu bulan tidak ada followers yang hilang sama sekali, beda dengan situs lain yang pernah saya coba.', 'Followers Instagram', 'Indonesia', 'ID'],
                ['Ayu Kartika', 5, 'Views Telegram datang tepat waktu, channel saya sekarang terlihat jauh lebih aktif.', 'Views Telegram', 'Indonesia', 'ID'],
                ['Dimas Saputra', 4, 'Pengirimannya mulai agak lambat dari yang diumumkan tapi support terus memberi kabar.', 'Followers Instagram', 'Malaysia', 'MY'],
                ['Nadia Safitri', 5, 'Murah, cepat, dan terpercaya, persis yang saya butuhkan untuk channel baru saya.', 'Member Telegram', 'Indonesia', 'ID'],
                ['Eko Purnomo', 5, 'Saya punya akun bisnis kecil dan situs ini benar-benar membantu engagement saya.', 'Likes Instagram', 'Indonesia', 'ID'],
                ['Citra Dewanti', 5, 'Saya pesan views YouTube untuk klien, datang bertahap dan terlihat sangat alami.', 'Views YouTube', 'Malaysia', 'MY'],
                ['Arif Hidayat', 5, 'Layanan terbaik yang pernah saya coba, tanpa berlebihan.', 'Followers TikTok', 'Indonesia', 'ID'],
            ],
            'ko' => [
                ['김서연', 5, '인스타그램 팔로워를 여러 번 주문했는데 항상 배송이 빠르게 시작되고 한 번도 빠진 적이 없어요.', '인스타그램 팔로워', '대한민국', 'KR'],
                ['이준호', 5, '텔레그램 조회수가 하루에 걸쳐 점진적으로 들어왔어요, 약속한 그대로요.', '텔레그램 조회수', '대한민국', 'KR'],
                ['박지민', 4, '품질은 좋았는데 배송이 생각보다 조금 늦게 시작됐어요.', '틱톡 팔로워', '대한민국', 'KR'],
                ['최민수', 5, '가격이 제가 찾아본 중에 제일 저렴하고 고객센터 응답도 빨라요.', '인스타그램 좋아요', '대한민국', 'KR'],
                ['정하은', 5, '제 텔레그램 채널 멤버를 구매했는데 자연스러운 성장에 정말 도움이 됐어요.', '텔레그램 멤버', '대한민국', 'KR'],
                ['강도현', 5, '몇 달째 이용 중인데 주문에 문제가 생긴 적이 한 번도 없어요.', '인스타그램 팔로워', '대한민국', 'KR'],
                ['윤서아', 4, '주말에는 고객센터 응답이 조금 늦었지만 결국 다 해결됐어요.', '스토리 조회수', '대한민국', 'KR'],
                ['임재현', 5, '팔로워 품질이 정말 좋아요, 빈 계정이 아니에요.', '틱톡 팔로워', '대한민국', 'KR'],
                ['한소영', 5, '인스타그램 쇼핑몰 하는 친구 두 명한테 추천했는데 둘 다 만족했어요.', '인스타그램 팔로워', '대한민국', 'KR'],
                ['오태윤', 5, '유튜브 조회수가 점진적으로 들어와서 아주 자연스러워 보였어요.', '유튜브 조회수', '대한민국', 'KR'],
                ['신유진', 5, '트위터 좋아요가 한 시간 안에 들어왔어요, 약속대로요.', '트위터 좋아요', '대한민국', 'KR'],
                ['배성민', 4, '전반적으로 좋은데 품질 옵션이 더 다양했으면 좋겠어요.', '유튜브 구독자', '대한민국', 'KR'],
                ['홍지우', 5, '이런 사이트를 처음 써봤는데 고객센터가 하나하나 다 도와줬어요.', '틱톡 좋아요', '대한민국', 'KR'],
                ['조현우', 5, '한 달 지나도 팔로워가 하나도 안 빠졌어요, 다른 사이트랑은 완전 달라요.', '인스타그램 팔로워', '대한민국', 'KR'],
                ['문채원', 5, '텔레그램 조회수가 정확히 시간 맞춰 들어와서 채널이 훨씬 활발해 보여요.', '텔레그램 조회수', '대한민국', 'KR'],
                ['서준영', 4, '배송이 안내보다 조금 느리게 시작됐지만 고객센터가 계속 알려줬어요.', '인스타그램 팔로워', '대한민국', 'KR'],
                ['남지호', 5, '저렴하고 빠르고 믿을 수 있어요, 새 채널에 딱 필요했던 서비스예요.', '텔레그램 멤버', '대한민국', 'KR'],
                ['권민지', 5, '작은 비즈니스 계정을 운영하는데 이 사이트가 참여도 높이는 데 정말 도움이 됐어요.', '인스타그램 좋아요', '대한민국', 'KR'],
                ['백승우', 5, '고객을 위해 유튜브 조회수를 주문했는데 점진적으로 들어와서 아주 자연스러웠어요.', '유튜브 조회수', '대한민국', 'KR'],
                ['유나영', 5, '지금까지 써본 것 중에 최고의 서비스예요, 과장 없이요.', '틱톡 팔로워', '대한민국', 'KR'],
            ],
            'zh' => [
                ['王芳', 5, '我已经订购过好几次Instagram粉丝了，每次都很快开始发货，也没有掉粉。', 'Instagram粉丝', '中国', 'CN'],
                ['李明', 5, 'Telegram浏览量在一整天内逐渐到账，跟承诺的一样。', 'Telegram浏览量', '中国', 'CN'],
                ['张丽', 4, '质量不错，就是发货比我预期的慢了一点。', 'TikTok粉丝', '台湾', 'TW'],
                ['陈伟', 5, '价格是我见过最便宜的，客服回复也很快。', 'Instagram点赞', '中国', 'CN'],
                ['刘洋', 5, '我给Telegram频道买了成员，确实帮助了自然增长。', 'Telegram成员', '新加坡', 'SG'],
                ['杨静', 5, '用这个网站好几个月了，从没遇到过订单问题。', 'Instagram粉丝', '中国', 'CN'],
                ['赵敏', 4, '周末客服回复慢了点，不过最后问题都解决了。', '故事浏览量', '台湾', 'TW'],
                ['黄强', 5, '粉丝质量真的很好，不是空账号。', 'TikTok粉丝', '中国', 'CN'],
                ['周婷', 5, '我把这个网站推荐给两个在Instagram开店的朋友，她们都很满意。', 'Instagram粉丝', '中国', 'CN'],
                ['吴磊', 5, 'YouTube观看量是逐渐到账的，看起来非常自然。', 'YouTube观看量', '中国', 'CN'],
                ['徐娟', 5, 'Twitter点赞一小时内就到了，跟说的完全一样。', 'Twitter点赞', '新加坡', 'SG'],
                ['孙涛', 4, '总体不错，就是希望能有更多质量选项。', 'YouTube订阅', '中国', 'CN'],
                ['马丽', 5, '这是我第一次用这种面板，客服每一步都很耐心帮我。', 'TikTok点赞', '中国', 'CN'],
                ['胡军', 5, '一个月后粉丝一个都没掉，跟我用过的其他网站完全不一样。', 'Instagram粉丝', '台湾', 'TW'],
                ['朱莉', 5, 'Telegram浏览量准时到账，频道现在看起来活跃多了。', 'Telegram浏览量', '中国', 'CN'],
                ['高峰', 4, '发货比公告的慢了一点，不过客服一直有跟我更新进度。', 'Instagram粉丝', '中国', 'CN'],
                ['林芳', 5, '便宜、快速又可靠，正是我新频道需要的。', 'Telegram成员', '中国', 'CN'],
                ['何斌', 5, '我有个小生意账号，这个网站真的帮助提高了互动。', 'Instagram点赞', '中国', 'CN'],
                ['罗雪', 5, '我给客户订购了YouTube观看量，逐渐到账，看起来很自然。', 'YouTube观看量', '新加坡', 'SG'],
                ['郑凯', 5, '我用过最好的服务，一点都不夸张。', 'TikTok粉丝', '中国', 'CN'],
            ],
            'ja' => [
                ['田中美咲', 5, 'Instagramのフォロワーを何度か注文しましたが、いつも配信が早く始まって減ったこともありません。', 'Instagramフォロワー', '日本', 'JP'],
                ['佐藤翔太', 5, 'Telegramの視聴回数が丸一日かけて徐々に届きました、約束通りです。', 'Telegram視聴回数', '日本', 'JP'],
                ['鈴木陽菜', 4, '品質は良かったですが、配信が思ったより少し遅く始まりました。', 'TikTokフォロワー', '日本', 'JP'],
                ['高橋大輝', 5, '価格は今まで見た中で一番安くて、サポートの返信も早いです。', 'Instagramいいね', '日本', 'JP'],
                ['伊藤結衣', 5, 'Telegramチャンネルのメンバーを購入しましたが、本当に自然な成長に役立ちました。', 'Telegramメンバー', '日本', 'JP'],
                ['渡辺蓮', 5, 'もう数ヶ月使っていますが、注文で問題が起きたことは一度もありません。', 'Instagramフォロワー', '日本', 'JP'],
                ['山本さくら', 4, '週末はサポートの返信が少し遅かったですが、最終的には解決しました。', 'ストーリー視聴', '日本', 'JP'],
                ['中村悠斗', 5, 'フォロワーの質が本当に良くて、空のアカウントじゃないです。', 'TikTokフォロワー', '日本', 'JP'],
                ['小林葵', 5, 'Instagramでお店をやっている友達二人に紹介したら、二人ともとても喜んでいました。', 'Instagramフォロワー', '日本', 'JP'],
                ['加藤颯太', 5, 'YouTubeの再生回数が徐々に増えていって、とても自然に見えました。', 'YouTube再生回数', '日本', 'JP'],
                ['吉田花', 5, 'Twitterのいいねが一時間以内に届きました、約束通りです。', 'Twitterいいね', '日本', 'JP'],
                ['山田健太', 4, '全体的には良いですが、もっと品質の選択肢があるといいなと思います。', 'YouTube登録者', '日本', 'JP'],
                ['佐々木舞', 5, 'こういうパネルを使うのは初めてでしたが、サポートが一つ一つ丁寧に教えてくれました。', 'TikTokいいね', '日本', 'JP'],
                ['松本大和', 5, '一ヶ月経ってもフォロワーが一人も減りませんでした、他のサイトとは全然違います。', 'Instagramフォロワー', '日本', 'JP'],
                ['井上心美', 5, 'Telegramの視聴回数がちょうど時間通りに届いて、チャンネルがずっと活発に見えます。', 'Telegram視聴回数', '日本', 'JP'],
                ['木村悠真', 4, '配信が発表より少し遅く始まりましたが、サポートがずっと状況を教えてくれました。', 'Instagramフォロワー', '日本', 'JP'],
                ['林美月', 5, '安くて早くて信頼できる、新しいチャンネルにまさに必要だったものです。', 'Telegramメンバー', '日本', 'JP'],
                ['斎藤蒼', 5, '小さいビジネスアカウントを持っていますが、このサイトは本当にエンゲージメント向上に役立ちました。', 'Instagramいいね', '日本', 'JP'],
                ['清水陽向', 5, 'クライアントのためにYouTube再生回数を注文しましたが、徐々に届いてとても自然でした。', 'YouTube再生回数', '日本', 'JP'],
                ['山口楓', 5, '今まで試した中で一番良いサービスです、誇張なしで。', 'TikTokフォロワー', '日本', 'JP'],
            ],
            'th' => [
                ['สมหญิง ใจดี', 5, 'สั่งผู้ติดตาม Instagram มาหลายครั้งแล้ว ทุกครั้งเริ่มส่งเร็วมากและไม่เคยลดเลย', 'ผู้ติดตาม Instagram', 'ไทย', 'TH'],
                ['ธนากร ศรีสุข', 5, 'ยอดวิว Telegram ทยอยเข้ามาตลอดทั้งวัน ตรงตามที่สัญญาไว้เป๊ะ', 'ยอดวิว Telegram', 'ไทย', 'TH'],
                ['พิมพ์ชนก แสงทอง', 4, 'คุณภาพดี แต่การส่งช้ากว่าที่คาดไว้นิดหน่อย', 'ผู้ติดตาม TikTok', 'ไทย', 'TH'],
                ['อนุชา รักไทย', 5, 'ราคาถูกที่สุดเท่าที่เคยเจอ และซัพพอร์ตตอบเร็วมาก', 'ไลค์ Instagram', 'ไทย', 'TH'],
                ['วรรณา พงษ์ไพร', 5, 'ซื้อสมาชิกให้ช่องเทเลแกรม ช่วยให้เติบโตแบบธรรมชาติได้จริงๆ', 'สมาชิก Telegram', 'ไทย', 'TH'],
                ['กิตติพงษ์ ทองดี', 5, 'ใช้เว็บนี้มาหลายเดือนแล้ว ไม่เคยมีปัญหากับออเดอร์เลย', 'ผู้ติดตาม Instagram', 'ไทย', 'TH'],
                ['สุนิสา จันทร์เพ็ญ', 4, 'ซัพพอร์ตตอบช้าหน่อยในวันหยุด แต่สุดท้ายก็แก้ปัญหาให้จนได้', 'ยอดวิวสตอรี่', 'ไทย', 'TH'],
                ['ประเสริฐ วงศ์ษา', 5, 'คุณภาพผู้ติดตามดีมาก ไม่ใช่บัญชีเปล่าๆ', 'ผู้ติดตาม TikTok', 'ไทย', 'TH'],
                ['นภัสสร บุญมี', 5, 'แนะนำเว็บนี้ให้เพื่อนสองคนที่ขายของใน Instagram ทั้งคู่ชอบมาก', 'ผู้ติดตาม Instagram', 'ไทย', 'TH'],
                ['ชัยวัฒน์ ศรีวิไล', 5, 'ยอดวิว YouTube ทยอยเข้ามา ดูเป็นธรรมชาติมาก', 'ยอดวิว YouTube', 'ไทย', 'TH'],
                ['อรุณี พรหมมา', 5, 'ไลค์ Twitter เข้ามาภายในหนึ่งชั่วโมง ตรงตามที่บอกไว้', 'ไลค์ Twitter', 'ไทย', 'TH'],
                ['ธีรพงศ์ อินทร์แก้ว', 4, 'โดยรวมดี แต่อยากให้มีตัวเลือกคุณภาพเพิ่มขึ้น', 'ผู้ติดตาม YouTube', 'ไทย', 'TH'],
                ['กาญจนา ทิพย์วงศ์', 5, 'เป็นครั้งแรกที่ใช้แผงแบบนี้ ซัพพอร์ตช่วยอธิบายทุกขั้นตอน', 'ไลค์ TikTok', 'ไทย', 'TH'],
                ['ณัฐพล เกียรติศักดิ์', 5, 'ผ่านไปเดือนหนึ่งผู้ติดตามไม่หายไปเลย ต่างจากเว็บอื่นที่เคยใช้', 'ผู้ติดตาม Instagram', 'ไทย', 'TH'],
                ['รัตนา สินธุ์เจริญ', 5, 'ยอดวิว Telegram เข้าตรงเวลาพอดี ช่องดูมีความเคลื่อนไหวมากขึ้นเยอะ', 'ยอดวิว Telegram', 'ไทย', 'TH'],
                ['วิชัย ประดิษฐ์', 4, 'เริ่มส่งช้ากว่าที่แจ้งไว้นิดหน่อย แต่ซัพพอร์ตแจ้งความคืบหน้าตลอด', 'ผู้ติดตาม Instagram', 'ไทย', 'TH'],
                ['สุพัตรา ชูเกียรติ', 5, 'ถูก เร็ว และเชื่อถือได้ ตรงกับที่ต้องการสำหรับช่องใหม่พอดี', 'สมาชิก Telegram', 'ไทย', 'TH'],
                ['ปิยะ วัฒนกุล', 5, 'มีบัญชีธุรกิจเล็กๆ เว็บนี้ช่วยเพิ่มการมีส่วนร่วมได้จริง', 'ไลค์ Instagram', 'ไทย', 'TH'],
                ['มาลี ศักดิ์สิทธิ์', 5, 'สั่งยอดวิว YouTube ให้ลูกค้า ทยอยเข้ามาและดูเป็นธรรมชาติมาก', 'ยอดวิว YouTube', 'ไทย', 'TH'],
                ['เอกชัย บุญเลิศ', 5, 'บริการที่ดีที่สุดเท่าที่เคยลองมา ไม่เกินจริงเลย', 'ผู้ติดตาม TikTok', 'ไทย', 'TH'],
            ],
            'vi' => [
                ['Nguyễn Thị Mai', 5, 'Tôi đã đặt follower Instagram nhiều lần rồi, lần nào cũng bắt đầu giao nhanh và không bao giờ bị tụt.', 'Follower Instagram', 'Việt Nam', 'VN'],
                ['Trần Văn Hùng', 5, 'Lượt xem Telegram đến dần trong suốt một ngày, đúng như đã hứa.', 'Lượt xem Telegram', 'Việt Nam', 'VN'],
                ['Lê Thị Hương', 4, 'Chất lượng tốt nhưng giao hàng chậm hơn tôi nghĩ một chút.', 'Follower TikTok', 'Việt Nam', 'VN'],
                ['Phạm Minh Tuấn', 5, 'Giá rẻ nhất mà tôi từng thấy và hỗ trợ trả lời rất nhanh.', 'Lượt thích Instagram', 'Việt Nam', 'VN'],
                ['Hoàng Thị Lan', 5, 'Tôi mua thành viên cho kênh Telegram của mình, thực sự giúp ích cho việc tăng trưởng tự nhiên.', 'Thành viên Telegram', 'Việt Nam', 'VN'],
                ['Vũ Đức Anh', 5, 'Dùng trang này mấy tháng rồi, chưa bao giờ gặp vấn đề với đơn hàng.', 'Follower Instagram', 'Việt Nam', 'VN'],
                ['Đặng Thị Thu', 4, 'Hỗ trợ trả lời hơi chậm vào cuối tuần nhưng cuối cùng cũng giải quyết xong.', 'Lượt xem story', 'Việt Nam', 'VN'],
                ['Bùi Văn Nam', 5, 'Chất lượng follower thực sự tốt, không phải tài khoản ảo.', 'Follower TikTok', 'Việt Nam', 'VN'],
                ['Ngô Thị Trang', 5, 'Tôi giới thiệu trang này cho hai người bạn có shop trên Instagram, cả hai đều rất hài lòng.', 'Follower Instagram', 'Việt Nam', 'VN'],
                ['Đỗ Quang Huy', 5, 'Lượt xem YouTube tăng dần dần, trông rất tự nhiên.', 'Lượt xem YouTube', 'Việt Nam', 'VN'],
                ['Trịnh Thị Ngọc', 5, 'Lượt thích Twitter đến trong vòng một giờ, đúng như đã hứa.', 'Lượt thích Twitter', 'Việt Nam', 'VN'],
                ['Lý Văn Phong', 4, 'Nhìn chung tốt, nhưng tôi muốn có thêm nhiều lựa chọn chất lượng hơn.', 'Subscriber YouTube', 'Việt Nam', 'VN'],
                ['Phan Thị Yến', 5, 'Đây là lần đầu tôi dùng loại trang như này, bên hỗ trợ giúp tôi từng bước một.', 'Lượt thích TikTok', 'Việt Nam', 'VN'],
                ['Đinh Công Sơn', 5, 'Sau một tháng không mất follower nào cả, khác hẳn những trang khác tôi từng dùng.', 'Follower Instagram', 'Việt Nam', 'VN'],
                ['Vương Thị Hạnh', 5, 'Lượt xem Telegram đến đúng giờ, kênh của tôi giờ trông năng động hơn nhiều.', 'Lượt xem Telegram', 'Việt Nam', 'VN'],
                ['Tô Minh Đức', 4, 'Giao hàng bắt đầu chậm hơn thông báo một chút nhưng hỗ trợ luôn cập nhật tình hình.', 'Follower Instagram', 'Việt Nam', 'VN'],
                ['Chu Thị Bích', 5, 'Rẻ, nhanh và đáng tin cậy, đúng thứ tôi cần cho kênh mới.', 'Thành viên Telegram', 'Việt Nam', 'VN'],
                ['Mai Văn Long', 5, 'Tôi có một tài khoản kinh doanh nhỏ và trang này thực sự giúp tăng tương tác.', 'Lượt thích Instagram', 'Việt Nam', 'VN'],
                ['Dương Thị Linh', 5, 'Tôi đặt lượt xem YouTube cho khách hàng, tăng dần và trông rất tự nhiên.', 'Lượt xem YouTube', 'Việt Nam', 'VN'],
                ['Hồ Văn Khánh', 5, 'Dịch vụ tốt nhất tôi từng thử, không nói quá chút nào.', 'Follower TikTok', 'Việt Nam', 'VN'],
            ],
            'pl' => [
                ['Zuzanna Kowalska', 5, 'Zamawiałam obserwujących na Instagramie już kilka razy, dostawa zawsze zaczyna się szybko i bez spadków.', 'Obserwujący Instagram', 'Polska', 'PL'],
                ['Jakub Nowak', 5, 'Wyświetlenia na Telegramie napływały stopniowo przez cały dzień, dokładnie tak jak obiecali.', 'Wyświetlenia Telegram', 'Polska', 'PL'],
                ['Julia Wiśniewska', 4, 'Jakość była dobra, ale dostawa zajęła trochę więcej czasu niż się spodziewałam.', 'Obserwujący TikTok', 'Polska', 'PL'],
                ['Michał Wójcik', 5, 'Ceny są najniższe jakie znalazłem, a wsparcie odpowiada bardzo szybko.', 'Polubienia Instagram', 'Polska', 'PL'],
                ['Natalia Kowalczyk', 5, 'Kupiłam członków do mojego kanału na Telegramie, naprawdę pomogło to organicznemu wzrostowi.', 'Członkowie Telegram', 'Polska', 'PL'],
                ['Piotr Kamiński', 5, 'Korzystam z tej strony od miesięcy, nigdy nie miałem problemu z zamówieniem.', 'Obserwujący Instagram', 'Polska', 'PL'],
                ['Alicja Lewandowska', 4, 'Wsparcie odpowiadało trochę wolniej w weekend, ale ostatecznie wszystko rozwiązali.', 'Wyświetlenia relacji', 'Polska', 'PL'],
                ['Tomasz Zieliński', 5, 'Jakość obserwujących jest naprawdę dobra, to nie są puste konta.', 'Obserwujący TikTok', 'Polska', 'PL'],
                ['Wiktoria Szymańska', 5, 'Poleciłam tę stronę dwóm znajomym z sklepami na Instagramie, obie były zachwycone.', 'Obserwujący Instagram', 'Polska', 'PL'],
                ['Kacper Woźniak', 5, 'Wyświetlenia na YouTube napływały stopniowo, wyglądało to bardzo naturalnie.', 'Wyświetlenia YouTube', 'Polska', 'PL'],
                ['Maja Dąbrowska', 5, 'Polubienia na Twitterze przyszły w mniej niż godzinę, dokładnie jak obiecano.', 'Polubienia Twitter', 'Polska', 'PL'],
                ['Filip Kozłowski', 4, 'Ogólnie dobrze, ale chciałbym mieć więcej opcji jakości.', 'Subskrybenci YouTube', 'Polska', 'PL'],
                ['Oliwia Jankowska', 5, 'To był mój pierwszy raz z takim panelem, wsparcie pomogło mi na każdym kroku.', 'Polubienia TikTok', 'Polska', 'PL'],
                ['Bartosz Mazur', 5, 'Po miesiącu nie straciłem ani jednego obserwującego, inaczej niż na innych stronach.', 'Obserwujący Instagram', 'Polska', 'PL'],
                ['Klaudia Krawczyk', 5, 'Wyświetlenia na Telegramie przyszły dokładnie na czas, mój kanał wygląda teraz o wiele bardziej aktywnie.', 'Wyświetlenia Telegram', 'Polska', 'PL'],
                ['Dawid Piotrowski', 4, 'Dostawa zaczęła się trochę wolniej niż zapowiadano, ale wsparcie informowało mnie na bieżąco.', 'Obserwujący Instagram', 'Polska', 'PL'],
                ['Weronika Grabowska', 5, 'Tanio, szybko i niezawodnie, dokładnie to czego potrzebowałam do nowego kanału.', 'Członkowie Telegram', 'Polska', 'PL'],
                ['Mateusz Pawłowski', 5, 'Mam małe konto biznesowe i ta strona naprawdę pomogła zwiększyć zaangażowanie.', 'Polubienia Instagram', 'Polska', 'PL'],
                ['Agata Michalska', 5, 'Zamówiłam wyświetlenia YouTube dla klienta, przychodziły stopniowo i wyglądały bardzo naturalnie.', 'Wyświetlenia YouTube', 'Polska', 'PL'],
                ['Krzysztof Adamski', 5, 'Najlepsza usługa jaką testowałem, bez przesady.', 'Obserwujący TikTok', 'Polska', 'PL'],
            ],
            'uk' => [
                ['Оксана Коваленко', 5, 'Замовляла підписників в Instagram вже кілька разів, доставка завжди починається швидко і без втрат.', 'Підписники Instagram', 'Україна', 'UA'],
                ['Андрій Бондаренко', 5, 'Перегляди в Telegram надходили поступово протягом цілого дня, точно як обіцяли.', 'Перегляди Telegram', 'Україна', 'UA'],
                ['Марія Ткаченко', 4, 'Якість була хороша, але доставка тривала трохи довше, ніж я очікувала.', 'Підписники TikTok', 'Україна', 'UA'],
                ['Олександр Кравченко', 5, 'Ціни найнижчі, які я знаходив, а підтримка відповідає дуже швидко.', 'Лайки Instagram', 'Україна', 'UA'],
                ['Юлія Мельник', 5, 'Купила учасників для свого каналу в Telegram, це справді допомогло органічному зростанню.', 'Учасники Telegram', 'Україна', 'UA'],
                ['Іван Шевченко', 5, 'Користуюся цим сайтом вже кілька місяців, жодного разу не було проблем із замовленням.', 'Підписники Instagram', 'Україна', 'UA'],
                ['Анна Поліщук', 4, 'Підтримка відповідала трохи повільніше у вихідні, але зрештою все вирішили.', 'Перегляди історій', 'Україна', 'UA'],
                ['Дмитро Савченко', 5, 'Якість підписників дійсно хороша, це не порожні акаунти.', 'Підписники TikTok', 'Україна', 'UA'],
                ['Наталія Романенко', 5, 'Порадила цей сайт двом подругам із магазинами в Instagram, обидві були в захваті.', 'Підписники Instagram', 'Україна', 'UA'],
                ['Максим Лисенко', 5, 'Перегляди на YouTube надходили поступово, виглядало дуже природно.', 'Перегляди YouTube', 'Україна', 'UA'],
                ['Вікторія Гончаренко', 5, 'Лайки в Twitter прийшли менш ніж за годину, точно як обіцяли.', 'Лайки Twitter', 'Україна', 'UA'],
                ['Сергій Марченко', 4, 'Загалом добре, але хотілося б більше варіантів якості.', 'Підписники YouTube', 'Україна', 'UA'],
                ['Тетяна Волошина', 5, 'Це був мій перший раз із такою панеллю, підтримка допомагала на кожному кроці.', 'Лайки TikTok', 'Україна', 'UA'],
                ['Роман Захарченко', 5, 'Через місяць жоден підписник не зник, на відміну від інших сайтів, які я пробував.', 'Підписники Instagram', 'Україна', 'UA'],
                ['Катерина Мороз', 5, 'Перегляди в Telegram прийшли точно вчасно, мій канал тепер виглядає набагато активнішим.', 'Перегляди Telegram', 'Україна', 'UA'],
                ['Артем Кузьменко', 4, 'Доставка почалася трохи повільніше, ніж заявлено, але підтримка постійно тримала мене в курсі.', 'Підписники Instagram', 'Україна', 'UA'],
                ['Софія Гриценко', 5, 'Дешево, швидко і надійно, саме те, що потрібно було для мого нового каналу.', 'Учасники Telegram', 'Україна', 'UA'],
                ['Богдан Руденко', 5, 'У мене невеликий бізнес-акаунт, і цей сайт справді допоміг з залученням.', 'Лайки Instagram', 'Україна', 'UA'],
                ['Ірина Тимошенко', 5, 'Замовила перегляди YouTube для клієнта, надходили поступово і виглядали дуже природно.', 'Перегляди YouTube', 'Україна', 'UA'],
                ['Владислав Іщенко', 5, 'Найкращий сервіс, який я коли-небудь пробував, без перебільшень.', 'Підписники TikTok', 'Україна', 'UA'],
            ],
        ];

        $rows = [];

        foreach ($reviewsByLang as $lang => $reviews) {
            foreach ($reviews as $sortOrder => $r) {
                $rows[] = [
                    'lang' => $lang,
                    'author_name' => $r[0],
                    'rating' => $r[1],
                    'body' => $r[2],
                    'related_service' => $r[3],
                    'country_name' => $r[4],
                    'country_code' => $r[5],
                    'is_approved' => true,
                    'sort_order' => $sortOrder,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
        }

        // Chunked - a single insert() with 340 rows of multi-byte text is well within MySQL's
        // default max_allowed_packet, but chunking keeps this safe on hosts with a smaller limit.
        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('reviews')->insert($chunk);
        }
    }

    public function down(): void
    {
        // Only removes what this migration added, not any review an admin has since written or
        // edited by hand - scoped by the exact set of languages this migration seeded.
        DB::table('reviews')->whereIn('lang', [
            'en', 'ar', 'tr', 'ru', 'es', 'fr', 'de', 'it', 'bp', 'id', 'ko', 'zh', 'ja', 'th', 'vi', 'pl', 'uk',
        ])->delete();
    }
};
