<div>
    @if (! $post)
        <p class="text-sm text-gray-500 dark:text-gray-400">This post no longer exists.</p>
    @else
        @if ($post->image_path)
            <img src="{{ \Illuminate\Support\Facades\Storage::disk('public')->url($post->image_path) }}" alt="" class="mb-4 w-full max-w-sm rounded-xl ring-1 ring-gray-950/10 dark:ring-white/10">
        @endif

        <p class="mb-1 text-xs font-medium text-gray-400 dark:text-gray-500">
            {{ \App\Filament\Pages\TelegramQueue::TYPE_FILTERS[$post->type] ?? $post->type }}
            @if ($post->image_source === 'ai_generated')
                · image generated by AI
            @elseif ($post->image_source === 'article')
                · image from the article
            @endif
        </p>

        <div class="whitespace-pre-wrap rounded-lg bg-gray-50 p-3 text-sm text-gray-700 dark:bg-white/5 dark:text-gray-300">{{ $post->message_text }}</div>

        <div class="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 text-xs text-gray-500 dark:text-gray-400">
            <div>
                <span class="font-medium text-gray-600 dark:text-gray-300">Scheduled:</span>
                {{ $post->scheduled_at->format('Y-m-d H:i') }} ({{ $post->scheduled_at->diffForHumans() }})
            </div>
            <div>
                <span class="font-medium text-gray-600 dark:text-gray-300">Status:</span>
                {{ ucfirst($post->status) }}
            </div>
            @if ($post->sent_at)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">Sent:</span>
                    {{ $post->sent_at->diffForHumans() }}
                </div>
            @endif
            @if ($post->ai_provider)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">AI:</span>
                    {{ $post->ai_provider }} ({{ $post->ai_model }})
                </div>
            @endif
            @if ($post->estimated_cost_usd !== null)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">Estimated cost:</span>
                    ${{ number_format((float) $post->estimated_cost_usd, 4) }}
                </div>
            @endif
        </div>

        @if ($post->error_message)
            <p class="mt-3 text-xs text-danger-600 dark:text-danger-400">{{ $post->error_message }}</p>
        @endif
    @endif
</div>
