<div>
    @if (! $post)
        <p class="text-sm text-gray-500 dark:text-gray-400">This post no longer exists.</p>
    @else
        @if ($post->image_path)
            <img src="{{ url('/telegram-images/'.$post->image_path) }}" alt="" class="mb-4 w-full max-w-sm rounded-xl ring-1 ring-gray-950/10 dark:ring-white/10">
        @elseif ($post->image_generation_error ?? null)
            <div class="mb-4 rounded-lg p-3 text-sm" style="background-color: rgba(var(--danger-500), .1); color: rgb(var(--danger-700))">
                <span class="font-medium">No image - AI generation failed:</span>
                {{ $post->image_generation_error }}
            </div>
        @endif

        <p class="mb-2 text-xs font-medium text-gray-400 dark:text-gray-500">
            {{ \App\Filament\Pages\TelegramQueue::TYPE_FILTERS[$post->type] ?? $post->type }}
            @if ($post->image_source === 'ai_generated')
                · image generated by AI
            @elseif ($post->image_source === 'article')
                · image from the article
            @elseif ($post->image_source === 'captured')
                · image captured from Telegram
            @elseif ($post->image_source === 'manual')
                · image uploaded manually
            @endif
        </p>

        <div class="rounded-lg bg-gray-50 p-3 text-sm text-gray-700 dark:bg-white/5 dark:text-gray-300" style="white-space: pre-wrap;">{{ $post->message_text }}</div>

        @if (in_array($post->status, ['pending', 'confirmed'], true))
            <div class="mt-3">
                <div class="mb-2 flex items-center justify-between text-xs text-gray-500 dark:text-gray-400">
                    <span>Time until publish</span>
                    <span>{{ $post->publishProgressPercent() }}%</span>
                </div>
                <div style="width: 100%; height: 6px; border-radius: 9999px; overflow: hidden; background-color: rgba(148,163,184,.25);">
                    <div style="width: {{ $post->publishProgressPercent() }}%; height: 100%; border-radius: 9999px; background-color: rgb(var(--primary-500)); transition: width .3s;"></div>
                </div>
            </div>
        @endif

        <div class="mt-3 text-xs text-gray-500 dark:text-gray-400" style="display: grid; grid-template-columns: 1fr 1fr; column-gap: 1rem; row-gap: .5rem;">
            <div>
                <span class="font-medium text-gray-600 dark:text-gray-300">Scheduled:</span>
                {{ $post->scheduled_at->format('Y-m-d H:i') }} ({{ $post->scheduled_at->diffForHumans() }})
            </div>
            <div>
                <span class="font-medium text-gray-600 dark:text-gray-300">Status:</span>
                {{ ucfirst($post->status) }}
            </div>
            @if ($post->sent_at)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">Sent:</span>
                    {{ $post->sent_at->diffForHumans() }}
                </div>
            @endif
            @if ($post->ai_provider)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">AI:</span>
                    {{ $post->ai_provider }} ({{ $post->ai_model }})
                </div>
            @endif
            @if ($post->estimated_cost_usd !== null)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">Text cost:</span>
                    ${{ number_format((float) $post->estimated_cost_usd, 4) }}
                </div>
            @endif
            @if ($post->image_cost_usd !== null)
                <div>
                    <span class="font-medium text-gray-600 dark:text-gray-300">Image cost:</span>
                    ${{ number_format((float) $post->image_cost_usd, 4) }}
                </div>
            @endif
        </div>

        @if ($post->error_message)
            <p class="mt-3 text-xs text-danger-600 dark:text-danger-400">{{ $post->error_message }}</p>
        @endif

        @php
            $canEdit = auth()->user()?->hasAccess(\App\Support\PanelSection::key(\App\Support\PanelSection::TELEGRAM, \App\Support\PanelSection::TIER_EDIT)) ?? false;
            $isSendable = in_array($post->status, ['pending', 'confirmed'], true);
        @endphp

        @if ($canEdit)
            <div class="mt-3 flex flex-wrap items-center gap-2">
                @if ($isSendable)
                    <x-filament::button
                        icon="heroicon-o-paper-airplane"
                        wire:click="sendNowPost({{ $post->id }})"
                        wire:confirm="Send this to the channel right now?"
                        wire:loading.attr="disabled"
                        wire:target="sendNowPost({{ $post->id }})"
                    >
                        Send now
                    </x-filament::button>

                    <x-filament::button
                        color="gray"
                        icon="heroicon-o-pencil-square"
                        x-on:click="$wire.unmountAction(); $wire.mountAction('editPost', {{ Illuminate\Support\Js::from(['postId' => $post->id]) }})"
                    >
                        Edit
                    </x-filament::button>
                @endif

                <x-filament::button
                    color="danger"
                    icon="heroicon-o-trash"
                    wire:click="deletePost({{ $post->id }})"
                    wire:confirm="{{ $post->status === 'sent' ? 'Delete this from history permanently? It\'s already been sent - this only removes the record.' : 'Delete this draft permanently?' }}"
                >
                    Delete
                </x-filament::button>
            </div>
        @endif
    @endif
</div>
